### ISSUE TITLE
Unify utils folder between different repositories

### ISSUE THREAD

**Issue by jakibaki** [varfish-org/varfish-server-worker#383]
**Is your feature request related to a problem? Please describe.**

Right now multiple repos contain identical files which is far from ideal as it involves keeping them in sync and keeping track of which files are duplicated where.

**Describe the solution you'd like**

I'd be in favour of a monorepo approach but that's just my personal opinion.

**Describe alternatives you've considered**

Making a seperate varfish-utils repo and having it be linked in via a git submodule or subtree would work too.

**Comment by holtgrewe** [comment]
I agree.

- `terraform` has already gone to the housekeeping repo already and could be deleted
- the protoc installer could go into a `varfish-utils` repository
